SET NAMES UTF8;
DROP DATABASE IF EXISTS 163music;
CREATE DATABASE banner CHARSET=UTF8;
USE 163music;
CREATE TABLE banner(
  iid SMALLINT PRIMARY KEY AUTO_INCREMENT,
  href VARCHAR NOT NULL,
  uptime DATE,
);
CREATE TABLE hot(
  lid SMALLINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR,
  href VARCHAR NOT NULL,
  
)